martin-lacheski/datos.txt
Por favor aceptar los datos, para concluir con la tarea solicitada
=> datos cargados

David-Atahualpa/archivo.txt
=> 1er commit en anexo_tp

Exequiel-Diaz/archivo.txt
Pull request del trabajo practico 2 de ingeniería en software 3, agregar estos cambios.
=> Primer commit

Nahuel Stempelatto/.txt.txt
Por favor incorporar estos cambios.
=> Commit externo

Nahuel-Wagner/misdatos.txt
=> trabajodos

Matias_Benitez/datosPersonales.txt
El bloc de notas contiene **nombre, apellido y número de legajo.**
=> Se agrego bloc de notas con datos personales

Sanchez-Emanuel/archivo.txt
se añadió la carpeta con el nombre Sanchez-Emanuel y un archivo con los datos correspondientes
=> se agrego la carpeta Sanchez-Emanuel y el archivo

Leon-Danilo/Archivo.txt
Por favor, incorporar estos cambios.
=> Carga de datos personales

Ferreira-Denis/Archivo.txt
Solicito que se agregue esta carpeta con mis datos personales. Saludos
=> Agregado un archivo de datos personales

Enrique-Gauto-Sand/archibo.txt
profe acepte para terminar el tp
=> Pull request de tp2 ingenieria de software 3

Carlos-Pereyra/archivo.txt
=> agregando cambios con mi nombre

Emanuel-Delgado/archivo.txt
=> Emanuel delgado

CristianSanchez/misdatos.txt, README.md
Por favor incorporar estos cambios. Gracias.
=> En la rama mis datos

De-Miranda-Norcelo-Gustavo/documento.txt
Commit agregado por Norcelo De Miranda.
=> Incorporar commit

mariano-ivasiuta/archivo.txt
Pull Request del TP1 de Ingeniería de software III.
=> Commit Ivasiuta Mariano - Confirmacion de cambios en el repositorio del TP 1

marcelo-kachuk/datos.txt
Pull request para TP-Versionado
=> Confirmo cambios en el repositorio

emiliano-blazco/archivo.txt
Pull request par el tp1 Ingenieria 3
=> Primera confirmacion de cambios para el TP1-Emiliano Blazco

belen-anton/contenido.txt
=> 1era confirmacion de cambios Anton Belen tp1

Camilo-Antunez/archivo.txt
=> Agregando archivo a rama pruebatp

Brian-Doubña/Datos.txt, Camilo-Antunez/archivo.txt, Exequiel-Brites/Datos.txt, Lucas-Colman/Datos.txt, README.md, Ramos-Federico/Archivo.txt, belen-anton/contenido.txt, emiliano-blazco/archivo.txt, fernandez-matias/datos.txt, marcelo-kachuk/datos.txt, mariano-ivasiuta/archivo.txt, martinez-alejandro/archivo_martinez.txt, mendoza-guadalupe/datos.txt
Conjunto de cambios para la versión 2024 del repositorio.
=> Versión 2024

laza-martinez/datos-credenciales.txt
=> Se agregan datos personales

Lujan-Facal/archivofacal.txt
=> Creando txt con mis datos

Pulikoski_Mauricio/File.txt
=> Pulikoski Mauricio - TP Versionado 2024

Carballo-Leonel/datos-leonel.txt
se agregan datos personales de Carballo Leonel
=> Agrega datos personales de leonel

Matias Damian Maciel/archivo.txt
solicito la revisión y aprobación de los cambios. Gracias
=> Se creo carpeta y archivo txt con los datos solicitados

Lisandro Leonardelli/Archivo.txt
=> Pull Request - Leonardelli Lisandro

Franco-Albornoz/Franco-Albornoz.txt
=> Pull Request - Albornoz Franco

luciano-castillo/luciano-castillo.txt
=> Creando la carpeta y archivo txt

Agustin-Erreguerena/archivo.txt
=> Entrega TP Agustín Erreguerena

Hernan-Lovera/archivo.txt
[TP GitHub - Hernán Lovera.docx](https://github.com/tinxo/IS3-TP-Versionado/files/14967875/TP.GitHub.-.Hernan.Lovera.docx)
[TP GitHub - Hernán Lovera.pdf](https://github.com/tinxo/IS3-TP-Versionado/files/14967876/TP.GitHub.-.Hernan.Lovera.pdf)
URL: https://github.com/Rayman64/IS3-TP-Versionado-Hern-n-Lovera-.git
=> TP GitHub - Hernán Lovera

archivo.txt
Buenas tardes profesor, Aca hago la entrega de la tarea solicitada.
Muchas gracias y disculpe las molestias.
=> se efectuaron los cambios

Aldo Amarilla/AldoAmarilla.txt
=> Pull Request Aldo Amarilla

Federico Piasecki/Nombre y datos.txt
intento de agregar nombre y datos
=> agregado nombre y datos

Bianca-Eitner/Bianca-Eitner.txt
=> Pull Request Bianca Eitner

Lucas-Pergher/datos.txt
Disculpe la confusión profesor, volví a realizar todos los pasos del trabajo practico siguiendo al pie la consigna. Si desea puede borrar el directorio "Lucas" ya que contiene los mismos datos que este.
=> Agregando mis datos personales

FabrizioPiloniV2/DatosPersonales.txt
Agrego la carpeta "FabrizioPiloniV2", para la reentrega del TP2
=> Nuevo Pull Request - Piloni Fabrizio

Facundo-Fraga/archivo.txt, Fraga/Fraga/archivo.txt
Vuelvo a entregar el tp2, se agrego la carpeta con mi nombre y apellido y el archivo txt dentro.
=> Nuevo Pull Request - Fraga Facundo

Milagros-Ernst/datos.txt
=> Entrega TP1

Donda-Melisa/datos.tx
Entrega del TP1 de IS3 - Donda, Melisa
=> TP1 - Donda

Roko-Guillermina/datos.txt
Agrego mi carpeta para el TP 1
=> Roko Guillermina - TP 1

Axel-Dos_Santos/archivo.txt
Pull Request hecho para el ejercicio 4 del TP1.
Made by: Axel Dos Santos
=> Pull Request Punto 4 - Axel Dos Santos

Benitez-Bautista/datos.txt
Agregado de datos del alumno Benitez Bautista para el TP1..
=> Agregado de datos del alumno Benitez Bautista para el TP1

Gabriel-Mittelstedt/Datos.txt
Desde una rama agregue un archivo .txt dentro de una carpeta con mis datos personales según lo solicitado en el TP y luego hice el merge con el main.
=> TP 1 - Mittelstedt

Juan-Manuel-Veron/datos.txt
Se agregó la carpeta personal Juan-Manuel-Veron con el archivo "datos.txt" en donde se incluye mi Apellido, Nombre y DNI.
=> Agregación de la carpeta personal.

Leandro-Escalada/datos.txt
Se realizo la creación de la carpeta y el archivo .txt con mis datos personales
=> pull request para realizar la entrega TP1

Maribel-Pereyra/datos.txt
=> TP1-versionado

Carolina-Munz/Datos.txt
Entrega del TP1 - Actualidad Informatica, Ingenieria del Software III- Carolina Munz
=> Creacion de archivo txt

Lautaro-Ifran/datos.txt
Entrega del trabajo práctico de versionado
=> TP1 Lautaro Ifran

Menacho-Natalia/datos.txt
Buenas noches, me gustaría unir los cambios que realicé como parte de la resolución del TP1 de Actualidad Informática. Se creó una carpeta y un archivo de texto con mis datos personales, y todo el proceso de realización del trabajo ha sido documentado en un archivo que se subirá al aula virtual.
=> Se agregó una carpeta y un .txt con mis datos personales

Francisco-Nuñez/datos.txt
=> TP1 INGENIERIA III

Martin-Maidana/datos.txt
- Nombre: Martin Maidana
- Legajo:  906557
- URL del fork: https://github.com/MartProf/IS3-TP-Versionado
- Se agregó carpeta personal con archivo de datos
- Contenido del archivo:
- Nombre completo
- Número de legajo
=> TP1 Ingeniería 3 - Martin Maidana

Paola_Samudio/datos.txt
=> Carpeta con datos personales

Karen-Proscopio/datos.text
Agregue carpeta con datos personales
=> TP 1 - Proscopio
